//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetDemo.rc
//
#define IDC_BTN_CYCLE_STOP_PLAY         3
#define IDC_BTN_CYCLE_STOP_CANCEL       4
#define IDC_BTN_CYCLE_CANCEL            4
#define IDR_MENU_LIVE_VIEW_RIGHT_MENU   4
#define IDM_ABOUTBOX                    0x0010
#define IDD_DLG_ABOUTBOX                100
#define IDS_ABOUTBOX                    101
#define IDD_NETDEMO_DIALOG              102
#define IDD_DLG_NETDEMO                 102
#define IDD_PRIMARY_NETDEMO             102
#define IDD_MAIN_NETDEMO                102
#define IDR_MAINFRAME                   128
#define IDR_MENU_DEVICE_TREE_R          129
#define IDD_DLG_ADD_DEVICE              130
#define IDD_DLG_PANNEL_PTZ              133
#define IDD_PANNEL_PTZ                  133
#define IDD_MENU_CFG                    137
#define IDD_CFG_DEVICE_BASIC            138
#define IDD_CHILD_CFG_NETWORK           139
#define IDD_CFG_NETWORK                 139
#define IDD_MENU_PLAYBACK               140
#define IDD_DLG_LOCAL_SETTING           141
#define IDD_DLG_CHILD_PTZ_EXTEND        142
#define IDD_DLG_PTZ_EXTEND              142
#define IDD_CFG_STREAM                  144
#define IDD_DLG_PLAY_CYCLE              145
#define IDD_DLG_CYCLE_MONITOR           145
#define IDI_FASTFORWARD_ENABLE          165
#define IDI_FASTBACKWARD_DISABLE        166
#define IDI_FASTFORWARD_DISABLE         167
#define IDI_SOUND_ENABLE                168
#define IDI_SOUND_DISABLE               169
#define IDI_PAUSE_DISABLE               172
#define IDI_STEP_ENABLE                 173
#define IDI_FASTBACKWARD_ENABLE         174
#define IDI_PAUSE_ENABLE                175
#define IDI_PLAY_ENABLE                 177
#define IDI_STEP_DISABLE                178
#define IDI_STOP_ENABLE                 179
#define IDI_STOP_DISABLE                180
#define IDI_PLAY_DISABLE                193
#define IDI_GOTOSTART_DISABLE           200
#define IDI_GOTOSTART_ENABLE            201
#define IDI_ICON1                       202
#define IDD_CFG_OSD                     203
#define IDD_MENU_ALARM                  204
#define IDD_MENU_MAINTAIN               205
#define IDD_CFG_IMAGE                   206
#define IDD_CFG_ALARM_IO                207
#define IDD_CFG_PRIVACY_MASK            208
#define IDR_MENU_DEVICE                 209
#define IDR_MENU_CHANNEL                210
#define IDD_DLG_DISCOVERY               213
#define IDD_CHILD_CFG_MOTION            214
#define IDB_BMP_TREE                    214
#define IDD_CFG_MOTION                  214
#define IDD_CFG_TAMPER                  215
#define IDB_BITMAP_DEVICE               216
#define IDB_BMP_DEV_LOCAL               216
#define IDD_MENU_VCA                    216
#define IDB_BITMAP_LOGIN                217
#define IDB_BMP_CHN_LOGIN               217
#define IDD_VCA_PEOPLE_COUNTING         217
#define IDB_BITMAP_CLOUD                218
#define IDI_ICON_LEFT                   218
#define IDB_BMP_DEV_CLOUD               218
#define IDD_DLG_PTZ_PRESET              218
#define IDR_MENU_LOGIN_TYPE             219
#define IDI_ICON_RIGHT                  219
#define IDD_DLG_CLOUD_DEV               219
#define IDI_ICON_UP                     220
#define IDB_BMP_MIC_STOP                220
#define IDR_MENU2                       221
#define IDI_ICON_DOWN                   221
#define IDB_BMP_DEV_CLOUD_LOGOUT        221
#define IDI_ICON_STOP                   222
#define IDB_BMP_CHN_LOGOUT              222
#define IDD_DLG_DOWNLOAD_INFO           222
#define IDI_ICON_LEFTUP                 223
#define IDB_BMP_DEV_LOCAL_LOGOUT        223
#define IDD_ALARM_REPORT                223
#define IDI_ICON_RIGHTUP                224
#define IDI_ICON_RIGHT_DOWN             225
#define IDI_ICON_RIGHTDOWN              225
#define IDB_BMP_MIC_START               225
#define IDI_ICON_LEFTDOWN               226
#define IDD_DLG_LOCAL_DEVICE_INFO       226
#define IDD_DLG_CLOUD_DEVICE_INFO       228
#define IDD_PANNEL_PLAYCONTROL          229
#define IDD_PANNEL_PLAY_CTRL            229
#define IDD_VCA_PEOPLE_COUNTING_STATISTICS 230
#define IDI_SNAPSHOT                    230
#define IDD_DLG_STREAM_CALLBACK         231
#define IDD_MENU_USERCFG                232
#define IDC_TREE_DEVICE_LIST            1001
#define IDC_BTN_PTZ_WIPER_ON            1002
#define IDC_BTN_3D_POSITION             1003
#define IDC_EDIT_LOG_PATH               1004
#define IDC_EDIT_PRESET_ID              1004
#define IDC_EDIT_CLOUD_URL              1004
#define IDC_BTN_PTZ_WIPER_OFF           1004
#define IDC_BUTTON_LEFTUP               1005
#define IDC_EDIT_SNAPSHOT_PATH          1005
#define IDC_EDIT_PRESET_NAME            1005
#define IDC_EDIT_CLOUD_USERNAME         1005
#define IDC_BTN_PTZ_LIGHT_ON            1005
#define IDC_EDIT_CYCLE_INTERVALTIME     1006
#define IDC_EDIT_CLOUD_PASSWD           1006
#define IDC_BTN_PTZ_LIGHT_OFF           1006
#define IDC_ADD_DEVICE                  1006
#define IDC_EDIT_FRAME_RATE             1007
#define IDC_BTN_PTZ_HEATER_ON           1007
#define IDC_EDIT_BIT_RATE               1008
#define IDC_BTN_PTZ_HEATER_OFF          1008
#define IDC_TAB_MAIN_MENU               1009
#define IDC_EDIT_GOP                    1009
#define IDC_BTN_PTZ_SNOWREMOVAL_ON      1009
#define IDC_EDIT_RES_WIDTH              1010
#define IDC_BTN_PTZ_SNOWREMOVAL_OFF     1010
#define IDC_LIST_ALL_LOG                1011
#define IDC_BTN_GET_ROUTE               1011
#define IDC_CLEAN_CLINTLOG              1012
#define IDC_EDIT_TIME_POS_Y             1012
#define IDC_BTN_START_RECORD_ROUTE      1012
#define IDC_SAVE_CLINETLOG              1013
#define IDC_EDIT_NAME_POS_X             1013
#define IDC_BTN_FOCUS_NEAR              1013
#define IDC_SCREEN_WINDOW               1014
#define IDC_EDIT_NAME_POS_Y             1014
#define IDC_BUTTON_STOP_DOWNLOAD        1014
#define IDC_IRIS_ON                     1014
#define IDC_EDIT_TEXT_1_POS_X           1015
#define IDC_BTN_FOCUS_NEAR3             1015
#define IDC_IRIS_OFF                    1015
#define IDC_EDIT_TEXT_1_POS_Y           1016
#define IDC_EDIT_TEXT_2_POS_X           1017
#define IDC_BTN_START_PATROL            1017
#define IDC_EDIT_TEXT_2_POS_Y           1018
#define IDC_BTN_STOP_PATROL             1018
#define IDC_EDIT_TEXT_3_POS_X           1019
#define IDC_BTN_SAVE_PATROL             1019
#define IDC_SAVE_PROTO_PORT             1020
#define IDC_EDIT_TEXT_3_POS_Y           1020
#define IDC_STATIC_PLAYCONTROL          1021
#define IDC_SAVE_NETWORK_CFG            1021
#define IDC_EDIT_TEXT_4_POS_X           1021
#define IDC_COMBO_CRUISE                1021
#define IDC_EDIT_TEXT_4_POS_Y           1022
#define IDC_COMBO_CYCLE_TYPE            1022
#define IDC_BTN_DELETE_PATROL           1022
#define IDC_COMBO_HTTPS_PORT_STATUS     1023
#define IDC_EDIT_TEXT_5_POS_X           1023
#define IDC_COMBO_ENCODE_FORMAT         1023
#define IDC_BTN_POINT_ADD               1023
#define IDC_EDIT_TEXT_5_POS_Y           1024
#define IDC_BTN_EDIT_POINT              1024
#define IDC_COMBO_SUPPORT_DHCP          1025
#define IDC_EDIT_TEXT_6_POS_X           1025
#define IDC_BTN_GET_PRESET              1025
#define IDC_BTN_STOP_RECORD_ROUTE       1025
#define IDC_COMBO_IP_TYPE               1026
#define IDC_BUTTON_SET_TIMEOUT          1026
#define IDC_BTN_START_ROUTE_PATROL      1026
#define IDC_SAVE_NTP_CFG                1027
#define IDC_EDIT_TEXT_6_POS_Y           1027
#define IDC_BUTTON_SET_OPREATION_LOG    1027
#define IDC_BTN_STOP_RECORD_PATROL      1027
#define IDC_PLAYCONTROL                 1028
#define IDC_COMBO_DATE_FORMAT           1028
#define IDC_REALPLAY                    1028
#define IDC_BTN_POINT_DEL               1028
#define IDC_BUTTON_SET_OPREATION_LOG2   1028
#define IDC_BTN_SAVE_STREAM_TYPE        1028
#define IDC_SNAPSHOT                    1029
#define IDC_COMBO_TIME_FORMAT           1029
#define IDC_BTN_GET_PATROL              1029
#define IDC_RECODER                     1030
#define IDC_LOCAL_RECODE                1030
#define IDC_MULTI_SCREEN                1031
#define IDC_COMBO_MULTI_SCREEN          1031
#define IDC_STATIC_MULTISCREEN          1032
#define IDC_SNAPSHOT2                   1033
#define IDC_STOP_PLAY                   1033
#define IDC_STOP_REALPLAY               1033
#define IDC_SCREEN_WINDOW_PLAYBACK      1034
#define IDC_STOP_REALPLAY2              1034
#define IDC_DATETIMEPICKER1             1036
#define IDC_DATE_BEGIN                  1036
#define IDC_DATETIMEPICKER_STATISTICAL_TIME 1036
#define IDC_DATETIMEPICKER2             1037
#define IDC_DATE_END                    1037
#define IDC_PLAYBACK_RECORD_LIST        1039
#define IDC_DATETIMEPICKER4             1041
#define IDC_TIME_BEGIN                  1041
#define IDC_DATETIMEPICKER5             1042
#define IDC_TIME_END                    1042
#define IDC_EDIT_ROUTE                  1043
#define IDC_EDIT_WAIT_TIME              1044
#define IDC_EDIT_RTSP_PORT              1045
#define IDC_EDIT_3D_STARTPOINT_Y        1045
#define IDC_BUTTON_PTZ_EXTEND           1046
#define IDC_EDIT_3D_STARTPOINT_X        1046
#define IDC_EDIT_SYNCHRONIZEINTERVAL    1046
#define IDC_DATETIMEPICKER3             1047
#define IDC_EDIT37                      1047
#define IDC_DATE_GOTO                   1047
#define IDC_EDIT_3D_ENDPOINT_Y          1047
#define IDC_DATETIMEPICKER6             1048
#define IDC_BUTTON1_PLAT_EXTEND         1048
#define IDC_TIME_GOTO                   1048
#define IDC_EDIT_3D_ENDPOINT_X          1048
#define IDC_EDIT_OSD_TEXT_4             1049
#define IDC_EDIT_POINT_STAYTIME         1049
#define IDC_TREE1                       1050
#define IDC_EDIT_OSD_TEXT_5             1050
#define IDC_EDIT_POINT_SPEED            1050
#define IDC_EDIT_OSD_TEXT_6             1051
#define IDC_EDIT_CRUISE                 1051
#define IDC_BTN_SET_PRESET              1052
#define IDC_CyclePlay                   1053
#define IDC_BTN_GOTO_PRESET             1053
#define IDC_CYCLEPLAY                   1053
#define IDC_BTN_DEL_PRESET              1054
#define IDC_RADIO_FORWARD               1055
#define IDC_SLIDER_SATURATION           1055
#define IDC_RADIO_REVERSE               1056
#define IDC_SLIDER_CONTRAST             1056
#define IDC_BUTTON_PLAYBACK_PLAY        1057
#define IDC_SLIDER_SHARPNESS            1057
#define IDC_BUTTON_PLAYBACK_PAUSE       1058
#define IDC_RADIO4                      1058
#define IDC_BUTTON_PLAYBACK_STOP        1059
#define IDC_RADIO5                      1059
#define IDC_BUTTON_PLAYBACK_SLOW        1060
#define IDC_RADIO6                      1060
#define IDC_BUTTON_PLAYBACK_FAST        1061
#define IDC_RADIO7                      1061
#define IDC_BUTTON_PLAYBACK_CAP         1062
#define IDC_RADIO8                      1062
#define IDC_BUTTON_PLAYBACK_SETBEGINPOS 1063
#define IDC_BUTTON_PLAYBACK_NEXTFRAME   1064
#define IDC_BUTTON_PLAYBACK_VOL         1065
#define IDC_BUTTON_LOCAL_SETTING        1066
#define IDC_SLIDER3                     1066
#define IDC_SLIDER_PLAY_PROGRESS        1066
#define IDC_TAB_WARNING                 1067
#define IDC_TAB_PRIMARYMENU             1068
#define IDC_BUTTON_PLAY_AUDIO           1070
#define IDC_PLAY_SOUND                  1070
#define IDC_SLIDER_SOUND                1071
#define IDC_SLIDER2                     1072
#define IDC_PLAY_MIC                    1072
#define IDC_SLIDER_SPEED                1072
#define IDC_SLIDER_SOUND2               1073
#define IDC_SLIDER_SOUND_MIC            1073
#define IDC_SLD_MIC_VOLUME              1073
#define IDC_LIST_PLAYBACK_DOWNLOAD_INFO 1077
#define IDC_BUTTON_DOWNLOADINFO         1078
#define IDC_LIST_CONFIGURE_DISKS_INFO   1080
#define IDC_LIST_DISKS_INFO             1080
#define IDC_LIST_ALARM_INPUT            1082
#define IDC_CHECK_ENABLE_OSD_TEXT_2     1082
#define IDC_TAB_VCA                     1083
#define IDC_CHECK_ENABLE_OSD_TEXT_3     1083
#define IDC_CHECK_ENABLE_OSD_TEXT_4     1084
#define IDC_BUTTON_LEFT                 1085
#define IDC_EDIT_IP                     1085
#define IDC_CHECK_ENABLE_OSD_TEXT_5     1085
#define IDC_BUTTON_RIGHT                1086
#define IDC_EDIT_PORT                   1086
#define IDC_CHECK_ENABLE_OSD_TEXT_6     1086
#define IDC_BUTTON_UP                   1087
#define IDC_EDIT_NAME                   1087
#define IDC_BUTTON_SAVE_OSD             1087
#define IDC_SAVE_OSD                    1087
#define IDC_BUTTON_PTZ_UP               1087
#define IDC_BUTTON_DOWN                 1088
#define IDC_EDIT_PASSWORD               1088
#define IDC_BUTTON_SAVE_SYSTEM_TIME     1088
#define IDC_SAVE_SYSTEM_TIME            1088
#define IDC_BUTTON_RIGHTUP              1089
#define IDC_BUTTON_SAVE_DEV_NAME        1089
#define IDC_SAVE_DEV_NAME               1089
#define IDC_CANCEL                      1089
#define IDC_BUTTON_LEFTDOWN             1090
#define IDC_EDIT_DEV_NAME               1090
#define IDC_LIST_CYCLE_SCREEN           1090
#define IDC_EDIT_PORT2                  1090
#define IDC_EDIT_IP_DOMAIN_NAME         1090
#define IDC_BUTTON_DISCOVERY            1091
#define IDC_SAVE_IMAGE_INFO             1091
#define IDC_LIST_CYCLE_ALLCHANNEL       1091
#define IDC_BUTTON_AUTO_DISCOVERY       1092
#define IDC_BUTTON_RIGHTDOWN            1092
#define IDC_EDIT_SATURATION             1092
#define IDC_SAVE_MOTION_CFG             1092
#define IDC_BUTTON_STOP                 1093
#define IDC_BUTTON_SAVE_ALARM_OUT_CFG   1093
#define IDC_EDIT_CONTRAST               1093
#define IDC_SAVE_ALARM_OUT_CFG          1093
#define IDC_BUTTON_PTZ_STOP             1093
#define IDC_LIST_DEVICE_LIST            1094
#define IDC_REFRESH                     1094
#define IDC_EDIT_SHARPNESS              1094
#define IDC_BUTTON_ADD_DAVICE           1095
#define IDC_TRIGGER_ALARM_OUT           1095
#define IDC_BUTTON_ADD_DEVICE           1095
#define IDC_EDIT_BEGIN_IP               1096
#define IDC_EDIT_END_IP                 1097
#define IDC_DEV_SYSTEM_DATE             1097
#define IDC_LIST_ALARM                  1098
#define IDC_DEV_SYSTEM_TIME             1098
#define IDC_LIST1                       1099
#define IDC_EVENT_QUERY_RECORD          1099
#define IDC_PASSENGER_FLOW_             1099
#define IDC_PASSENGER_FLOW_LIST         1099
#define IDC_LIST_USER_LIST              1099
#define IDC_COMBO_EVENT_LIST            1100
#define IDC_BUTTON_SET_PLAY_TIME        1101
#define IDC_SLD_SOUND_VOLUME            1102
#define IDC_CHECK_EDNABLE_DHCP          1102
#define IDC_EDIT_MTU                    1103
#define IDC_EDIT_HTTP_PORT              1104
#define IDC_EDIT_HTTPS_PORT             1105
#define IDC_COMBO_HTTP_PORT_STATUS      1106
#define IDC_COMBO_RTSP_PORT_STATUS      1107
#define IDC_CHECK_EDNABLE_DHCP2         1108
#define IDC_CHECK_EDNABLE_NTP_DHCP      1108
#define IDC_CHECK_EDNABLE_NTP_SERVER    1108
#define IDC_EDIT_NTP_SERVER_DOMAINNAME  1109
#define IDC_EDIT_NTP_DOMAINNAME         1109
#define IDC_SLIDER_BRIGHTNESS           1110
#define IDC_EDIT_NTP_SERVER_PORT        1110
#define IDC_EDIT_NTP_PORT               1110
#define IDC_EDIT_BRIGHTNESS             1111
#define IDC_RESRESH                     1112
#define IDC_REFRESH_IMAGE_CFG           1112
#define IDC_SLIDER_SENSITIVITY          1119
#define IDC_EDIT_OBJ_SIZE               1120
#define IDC_EDIT_HISTORY                1121
#define IDC_SLIDER_OBJ_SIZE             1122
#define IDC_SLIDER_HISTORY              1123
#define IDC_SAVE_VIDEO_STREAM           1126
#define IDC_SAVE_TEMPER_CFG             1127
#define IDC_SAVE_PRIVACY_MASK           1133
#define IDC_DELETE_PRIVACY_MASK         1134
#define IDC_COMBO_ALARM_OUTPUT_INDEX    1136
#define IDC_ADD_PRIVACY_MASK            1136
#define IDC_EDIT_ALARM_OUTPUT_NAME      1137
#define IDC_COMBO_ALARM_OUTPUT_STATUS   1138
#define IDC_EDIT_ALARM_OUTPUT_CHN_ID    1139
#define IDC_EDIT_ALARM_OUTPUT_DURATION  1140
#define IDC_CHECK_ENABLE_TIME           1141
#define IDC_CHECK_ENABLE_NAME           1142
#define IDC_CHECK_ENABLE_OSD_TEXT_1     1143
#define IDC_EDIT_OSD_NAME               1144
#define IDC_EDIT_OSD_TEXT_1             1145
#define IDC_EDIT_OSD_TEXT_2             1146
#define IDC_EDIT_OSD_TEXT_3             1147
#define IDC_EDIT_TIME_POS_X             1148
#define IDC_BUTTON_REBOOT               1149
#define IDC_COMBO_STREAM_INDEX          1149
#define IDC_BUTTON_FACTORY_DEFAULT      1150
#define IDC_EDIT_RES_HIGHT              1151
#define IDC_COMBO_QUALITY               1152
#define IDC_COMBO_TIME_ZONE             1153
#define IDC_BUTTON_SET_LOGPATH          1154
#define IDC_BUTTON_SET_LOCAL_RECORD_PATH 1155
#define IDC_COMBO_WIN_INDEX             1155
#define IDC_BUTTON_SET_KEEPLIVE         1156
#define IDC_BTN_CYCLE_SAVE              1156
#define IDC_EDIT_RECORD_PATH            1157
#define IDC_BTN_CYCLE_ADDALL            1157
#define IDC_EDIT_TRY_TIME               1158
#define IDC_BTN_CYCLE_ADD               1158
#define IDC_EDIT_RECEIVE_TIMEOUT        1159
#define IDC_BTN_CYCLE_DEL               1159
#define IDC_EDIT_FILE_TIMEOUT           1160
#define IDC_BTN_DELALL                  1160
#define IDC_CHECK_AUTO_SAVE_LOG         1161
#define IDC_COMBO_PRESET                1161
#define IDC_CHECK_FAILURE_LOG           1162
#define IDC_BTN_FOCUS_IN                1162
#define IDC_BTN_ZOOM_IN                 1162
#define IDC_CHECK_SUCCESSFUL_LOG        1163
#define IDC_BTN_FOCUS_OUT               1163
#define IDC_BTN_ZOOM_OUT                1163
#define IDC_BUTTON_PASSENGER_FLOW_SET_CALLBACK 1164
#define IDC_BTN_FOCUS_FAR               1164
#define IDC_REGISTER_PASSENGER_FLOW_SET_CALLBACK 1164
#define IDC_BUTTON_CLOUD_SAVE           1165
#define IDC_BTN_FOCUS_FAR2              1165
#define IDC_BTN_FOCUS_STOP              1165
#define IDC_BUTTON_CLOUD_CANCEL         1166
#define IDC_UNREGISTER_PASSENGER_FLOW_SET_CALLBACK 1166
#define IDC_COMBO_EXTEND_PRESET         1167
#define IDC_LIST_CRUISE                 1168
#define IDC_UNREGISTER_PASSENGER_FLOW_SET_CALLBACK2 1168
#define IDC_CLEAR_PASSENGER_FLOW_LIST   1168
#define IDC_STATIC_PLAY_CONTROL         1169
#define IDC_STATIC_PLAY_CONTROL2        1170
#define IDC_STATIC_PLAY_WINNUM          1170
#define IDC_BUTTON_START_DEMNLOAD       1170
#define IDC_STATIC_SOUND_CONTROL        1171
#define IDC_EDIT_SENSITIVITY            1171
#define IDC_IPADD_BEGIN_IP              1171
#define IDC_IPADD_END_IP                1172
#define IDC_LIST_PRIVACY_MASK           1172
#define IDC_IPADD_GATEWAY               1172
#define IDC_EDIT1                       1173
#define IDC_IPADD_NTP_SERVER_IP         1173
#define IDC_EDIT_USER_NAME              1173
#define IDC_EDIT_TIME_POINT             1173
#define IDC_EDIT_RECORD_STATUS          1173
#define IDC_EDIT_USERNAME               1173
#define IDC_EDIT_SUB_ITEM               1174
#define IDC_EDIT2                       1174
#define IDC_BUTTON_CLEAN_ALL            1174
#define IDC_IPADD_SUB_NETMASK           1174
#define IDC_EDIT_USERPASSWORD           1174
#define IDC_LOCAL_ATTRIBUTE_IP          1175
#define IDC_IPADD_IPV4                  1175
#define IDC_EDIT_USERNAME2              1175
#define IDC_LOCAL_ATTRIBUTE_PORT        1176
#define IDC_EDIT_PTZ_PRESET_NAME        1176
#define IDC_EDIT_USERPASSWORD2          1176
#define IDC_LOCAL_ATTRIBUTE_NAME        1177
#define IDC_BTN_CANCEL                  1177
#define IDC_EDIT_USERPASSWORD3          1177
#define IDC_LOCAL_ATTRIBUTE_DEVTYPE     1178
#define IDC_PASSENGER_FLOW_TABLE        1178
#define IDC_LOCAL_ATTRIBUTE_ALARM_INPUTNUM 1179
#define IDC_STATIC_REPORT_TYPE          1179
#define IDC_LOCAL_ATTRIBUTE_ALARM_OUTPUTNUM 1180
#define IDC_STATIC_COUNTING_TYPE        1180
#define IDC_LOCAL_ATTRIBUTE_SAVE        1181
#define IDC_STATIC_STATISTICAL_TIME     1181
#define IDC_LOCAL_ATTRIBUTE_CANCEL      1182
#define IDC_LOCAL_ATTRIBUTE_ALARM_INPUTNUM2 1183
#define IDC_LOCAL_ATTRIBUTE_ALARM_CHANNELNUM 1184
#define IDC_CLOUD_ATTRIBUTE_URL         1185
#define IDC_COMBO_REPORT_TYPE           1185
#define IDC_LOCAL_ATTRIBUTE_PWD         1186
#define IDC_COMBO2                      1186
#define IDC_COMBO_COUNTING_TYPE         1186
#define IDC_COMBO_USERTYPELIST          1186
#define IDC_CLOUD_ATTRIBUTE_USER        1187
#define IDC_BUTTON_COUNT_PEOPLE         1187
#define IDC_COMBO_USERTYPELIST2         1187
#define IDC_CLOUD_ATTRIBUTE_USER_PWD    1188
#define IDC_CLOUD_ATTRIBUTE_DEV_IP      1189
#define IDC_CLOUD_ATTRIBUTE_DEV_PORT    1190
#define IDC_COMBO1                      1190
#define IDC_CLOUD_ATTRIBUTE_DEV_USER    1191
#define IDC_CLOUD_ATTRIBUTE_DEV_NAME    1192
#define IDC_IPADD_LOCAL_ATTRIBUTE       1192
#define IDC_CLOUD_ATTRIBUTE_DEV_MODEL   1193
#define IDC_CLOUD_ATTRIBUTE_DEV_SERIAL  1194
#define IDC_CLOUD_ATTRIBUTE_ORG_ID      1195
#define IDC_CLOUD_ATTRIBUTE_SAVE        1196
#define IDC_CLOUD_ATTRIBUTE_CANCEL      1197
#define IDC_LAB_DEVICE_NUM              1197
#define IDC_EDIT_EXTEND_PRESET_NAME     1198
#define IDC_TEXT_PLAYBACK_SPEED         1198
#define IDC_TEXT_PLAYBACK_REMAIN_TIME   1199
#define IDC_PLAYBACK_REMAIN_TIME        1200
#define IDC_PLAYBACK_CURRENT_TIME       1203
#define IDC_EDIT_AREA_X8                1203
#define IDC_EDIT_AREA_Y8                1204
#define IDC_COMBO_AREA_ALIGN1           1205
#define IDC_COMBO_AREA_ALIGN2           1206
#define IDC_COMBO_AREA_ALIGN3           1208
#define IDC_EDIT3                       1210
#define IDC_EDIT_FONT_COLOR             1210
#define IDC_EDIT_OSD_CONTENT_TEXT1      1211
#define IDC_BUTTON_START_RECORD         1211
#define IDC_COMBO_AREA_ALIGN4           1212
#define IDC_BUTTON2                     1212
#define IDC_BUTTON_STOP_RECORD          1212
#define IDC_BUTTON_                     1212
#define IDC_BUTTON_REALTIME_CLOSE       1212
#define IDC_BUTTON_GETUSER              1212
#define IDC_BUTTON_MODIFY_USER          1212
#define IDC_BUTTON_GETRECORDDAYNUMS     1212
#define IDC_EDIT_OSD_CONTENT_TEXT3      1213
#define IDC_BUTTON_STREAM_CALLBACK      1213
#define IDC_EDIT_OSD_CONTENT_TEXT4      1214
#define IDC_BUTTON_REALTIME_REG         1214
#define IDC_EDIT_OSD_CONTENT_TEXT2      1215
#define IDC_BUTTON_DECODE_REG           1215
#define IDC_CHECK_OSD_ENABLE1           1216
#define IDC_BUTTON_DECODE_CLOSE         1216
#define IDC_CHECK_OSD_ENABLE2           1217
#define IDC_BUTTON_DISPLAY_REG          1217
#define IDC_CHECK_OSD_ENABLE3           1218
#define IDC_BUTTON_DISPLAY_CLOSE        1218
#define IDC_CHECK_OSD_ENABLE4           1219
#define IDC_BUTTON_FRAME_REG            1219
#define IDC_CHECK_OSD_ENABLE5           1220
#define IDC_BUTTON_FRAME_CLOSE          1220
#define IDC_CHECK_OSD_ENABLE6           1221
#define IDC_RADIO_MAIN_STREAM           1221
#define IDC_CHECK_OSD_ENABLE7           1222
#define IDC_RADIO_THIRD_STREAM          1222
#define IDC_BUTTON_GETUSERLIST          1222
#define IDC_CHECK_OSD_ENABLE8           1223
#define IDC_RADIO_SUB_STREAM            1223
#define IDC_BUTTON_MODIFYUSER           1223
#define IDC_COMBO_AREA_ALIGN5           1224
#define IDC_BUTTON_ADDUSER              1224
#define IDC_EDIT_OSD_CONTENT_TEXT5      1225
#define IDC_BUTTON5                     1225
#define IDC_BUTTON_DELUSER              1225
#define IDC_EDIT_OSD_CONTENT_TEXT6      1226
#define IDC_STATIC_USER_LIST            1226
#define IDC_EDIT_OSD_CONTENT_TEXT8      1227
#define IDC_BUTTON_GET_USER_LIST        1227
#define IDC_EDIT_OSD_CONTENT_TEXT7      1228
#define IDC_BUTTON_DELETE_USER          1228
#define IDC_COMBO_AREA_ALIGN6           1229
#define IDC_BUTTON_GET_USER_LIST2       1229
#define IDC_BUTTON_ADD_USER             1229
#define IDC_COMBO_AREA_ALIGN7           1230
#define IDC_STATIC_ADDUSER              1230
#define IDC_COMBO_AREA_ALIGN8           1231
#define IDC_STATIC_USERNAME             1232
#define IDC_STATIC_USERTYPE             1233
#define IDC_STATIC_USERPASSWORD         1234
#define IDC_STATIC_MODIFYUSER           1235
#define IDC_STATIC_USERNAME2            1236
#define IDC_STATIC_RECORDDAYNUMS        1236
#define IDC_STATIC_USERPASSWORD2        1237
#define IDC_BUTTON1                     1237
#define IDC_STATIC_USERPASSWORD3        1238
#define IDC_STATIC_USERTYPE2            1239
#define IDC_STATIC_MODIFYUSER_NOTE      1240
#define ID_32771                        32771
#define ID_DEVICEOPER_32772             32772
#define ID_DEVICEOPER_32773             32773
#define ID_DEVICEOPER_32774             32774
#define ID_DEVICEOPER_32775             32775
#define ID_DEVICEOPER_32776             32776
#define ID_DEVICEOPER_32777             32777
#define ID_Menu                         32778
#define ID_DEVICEOPER_32779             32779
#define ID_CHANNEL_32780                32780
#define ID_PALYRIGHTCLICK_32781         32781
#define ID_PALYRIGHTCLICK_32782         32782
#define ID_PALYRIGHTCLICK_32783         32783
#define ID_PALYRIGHTCLICK_FULLSCREEN    32784
#define ID_PALYRIGHTCLICK_MULITSCREEN   32785
#define ID_PALYRIGHTCLICK_AUTOADJUST    32786
#define ID_DEVICEOPER_LOG               32787
#define ID_DEVICEOPER_LOGIN             32788
#define ID_Menu32789                    32789
#define ID_PALYRIGHTCLICK_32790         32790
#define ID_Menu32791                    32791
#define ID_PALYRIGHTCLICK_32792         32792
#define ID_PLAY_REAL                    32793
#define ID_32794                        32794
#define ID_PALYRIGHTCLICK_32795         32795
#define LOGIN_TYPE                      32796
#define ID_DEVICEOPER_DELETE            32796
#define ID_32793                        32797
#define ID_DEVICEOPER_32797             32797
#define ID_LOGIN_32794                  32798
#define ID_DEVICEOPER_DEVICEINFO        32798
#define ID_LOGIN_32795                  32799
#define ID_PALYRIGHTCLICK_STOP          32799
#define ID_LOGIN_CLOUD                  32800
#define ID_PALY_RIGHTCLICK_STOPVIDEO    32800
#define ID_LOGIN_32797                  32801
#define ID_PALY_RIGHTCLICK_NETDELAY_REAL 32801
#define ID_LOGIN_DEVICE                 32802
#define ID_PALY_RIGHTCLICK_NETDELAY_FLUENT 32802
#define ID_PALY_RCLICK_KEYFRAME         32803
#define ID_PALY_RIGHTCLICK_TALK         32804
#define ID_MENU_LOGIN_CLOUD             32805
#define ID_MENU_LOGIN_DEVICE            32806
#define ID_DEVICEOPER_LOGOUT            32807
#define ID_MENU_DEVICEOPER_ATTRIBUTE    32808
#define ID_PALYRIGHTCLICK_STOPALL       32809
#define ID_PALYRIGHTCLICK_CAMERAINFO    32810
#define ID_PALYRIGHTCLICK_3DPOSITION    32812
#define ID_Menu32813                    32813
#define ID_PALYRIGHTCLICK_DZ            32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        233
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1238
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
